import { Component, Input } from '@angular/core';
import { Project } from 'src/app/models/project.model';

@Component({
  selector: 'app-tickets',
  templateUrl: './tickets.component.html',
  styleUrls: ['./tickets.component.scss'],
})
export class TicketsComponent {
  @Input() project!: Project;
  tickets = [
    {
      _id: '9384573498',
      name: 'Test ticket',
      description: 'This is a test ticket',
      status: 'pending',
      priority: 'high',
      type: 'bug',
      dateCreated: 'blablabla',
      dateClosed: null,
      project: 'projectId',
      author: 'AuthorId',
      assignedTo: [],
      modifications: [],
    },
    {
      _id: '9384573498',
      name: 'Test ticket',
      description: 'This is a test ticket',
      status: 'active',
      priority: 'low',
      type: 'bug',
      dateCreated: 'blablabla',
      dateClosed: null,
      project: 'projectId',
      author: 'AuthorId',
      assignedTo: [],
      modifications: [],
    },
    {
      _id: '9384573498',
      name: 'Test ticket',
      description: 'This is a test ticket',
      status: 'closed',
      priority: 'medium',
      type: 'feature request',
      dateCreated: 'blablabla',
      dateClosed: null,
      project: 'projectId',
      author: 'AuthorId',
      assignedTo: [],
      modifications: [],
    },
    {
      _id: '9384573498',
      name: 'Test ticket',
      description: 'This is a test ticket',
      status: 'pending',
      priority: 'immediate',
      type: 'bug',
      dateCreated: 'blablabla',
      dateClosed: null,
      project: 'projectId',
      author: 'AuthorId',
      assignedTo: [],
      modifications: [],
    },
    {
      _id: '9384573498',
      name: 'Test ticket',
      description: 'This is a test ticket',
      status: 'pending',
      priority: 'high',
      type: 'bug',
      dateCreated: 'blablabla',
      dateClosed: null,
      project: 'projectId',
      author: 'AuthorId',
      assignedTo: [],
      modifications: [],
    },
    {
      _id: '9384573498',
      name: 'Test ticket',
      description: 'This is a test ticket',
      status: 'pending',
      priority: 'high',
      type: 'bug',
      dateCreated: 'blablabla',
      dateClosed: null,
      project: 'projectId',
      author: 'AuthorId',
      assignedTo: [],
      modifications: [],
    },
    {
      _id: '9384573498',
      name: 'Test ticket',
      description: 'This is a test ticket',
      status: 'pending',
      priority: 'high',
      type: 'bug',
      dateCreated: 'blablabla',
      dateClosed: null,
      project: 'projectId',
      author: 'AuthorId',
      assignedTo: [],
      modifications: [],
    },
  ];

  constructor() {}
}
